#!/bin/sh

# install common extensions

code --install-extension aaron-bond.better-comments
code --install-extension christian-kohler.npm-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dunstontc.dark-plus-syntax
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.terminal
code --install-extension liviuschera.noctis
code --install-extension mariusschulz.yarn-lock-syntax
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension robertohuertasm.vscode-icons
code --install-extension shalldie.background
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vsmobile.vscode-react-native
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extention burkeholland.simple-react-snippets
code --install-extention flowtype.flow-for-vscode
code --install-extention jpoissonnier.vscode-styled-components
code --install-extention tyriar.sort-lines

# fix the font
rm ~/library/fonts/FiraCode-Bold.otf

# copy settings

cp ~/dotfiles/vscode/* ~/library/Application\ Support/Code/User